{{- if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "seat-coc-page.fullname" . }}
  labels:
    {{- include "seat-coc-page.labels" . | nindent 4 }}
  {{- with .Values.route.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.route.host }}
  host: {{ . | quote }}
  {{- end }}
  to:
    kind: Service
    name: {{ include "seat-coc-page.fullname" . }}
  port:
    targetPort: http
  {{- with .Values.route.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
