{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "seat-coc-page.serviceAccountName" . }}
  labels:
    {{- include "seat-coc-page.labels" . | nindent 4 }}
{{- end }}
